/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false src/worker-configuration.d.ts` (hash: d6035aaf8dbf6c789b493a6c4f070b27)
interface __BaseEnv_Env {
  DB: D1Database;
  ASSETS: Fetcher;
  CRON_MAX_FEEDS: string;
  OGP_MAX_ITEMS_PER_FEED: string;
  SUMMARY_MAX_ITEMS_PER_FEED: string;
  SUMMARY_API_BASE_URL: string;
  SUMMARY_MODEL: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "CRON_MAX_FEEDS"
      | "OGP_MAX_ITEMS_PER_FEED"
      | "SUMMARY_MAX_ITEMS_PER_FEED"
      | "SUMMARY_API_BASE_URL"
      | "SUMMARY_MODEL"
    >
  > {}
}
